# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a80db4ba2fe439436e641064762c764078976bc344c18537cdf201d0aaffb9a08dfef8874547470467389b1cb78c7035091de756644a0d99ecd51f88bf9d1089

test:
  secret_key_base: fd1e57480dfcd2fc6daf3595093b90763cf4e0ed04d39d5c46e11470da38b50bec34e34cc6bd34bfa3cf6a59c17fc5d59a344e37422a32a689e0a2745d2efbe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
